version: "3"

services:
  graphdb:
    image: arangodb:3.8.5
    platform: linux/amd64
    environment:
      - ARANGO_ROOT_PASSWORD=
    ports:
      - 8529:8529
    volumes:
      - resoto_graphdb_data:/var/lib/arangodb3
  resotocore:
    image: somecr.io/someengineering/resotocore:2.0.0a16
    depends_on:
      - graphdb
    ports:
      - 8900:8900
    environment:
      - PSK
      - RESOTOCORE_HOST=resotocore
      - RESOTOCORE_START_COLLECT_ON_SUBSCRIBER_CONNECT=true
      - RESOTOCORE_GRAPHDB_SERVER=http://graphdb:8529
      - RESOTOCORE_GRAPHDB_PASSWORD=changeme
    restart: always
    stop_grace_period: 2m
  resotoworker: 
    image: somecr.io/someengineering/resotoworker:2.0.0a16
    depends_on:
      - resotocore
    ports:
      - 9956:9956
    environment:
      - PSK
      - RESOTOWORKER_RESOTOCORE_URI=http://resotocore:8900
      - RESOTOWORKER_RESOTOCORE_WS_URI=ws://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotometrics: 
    image: somecr.io/someengineering/resotometrics::2.0.0a16
    depends_on:
      - resotocore
    ports:
      - 9955:9955
    environment:
      - PSK
      - RESOTOMETRICS_RESOTOCORE_URI=http://resotocore:8900
      - RESOTOMETRICS_RESOTOCORE_WS_URI=ws://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotoshell: 
    image: somecr.io/someengineering/resotoshell:2.0.0a16
    depends_on:
      - resotocore
    environment:
      - PSK
      - RESOTOSHELL_RESOTOCORE_URI=http://resotocore:8900
      - RESOTOSHELL_RESOTOCORE_WS_URI=ws://resotocore:8900
    restart: always
    stop_grace_period: 2m
volumes:
  resoto_graphdb_data:
