version: "3"

services:
  graphdb:
    image: arangodb:3.8.6
    platform: linux/amd64
    environment:
      - ARANGO_ROOT_PASSWORD=
    ports:
      - 8529:8529
    volumes:
      - resoto_graphdb_data:/var/lib/arangodb3
  tsdb:
    image: prom/prometheus:v2.33.4
    ports:
      - 9090:9090
    volumes:
      - ./dockerV2/prometheus.yml:/etc/prometheus/prometheus.yml
      - resoto_tsdb_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=730d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
  resotocore:
    image: somecr.io/someengineering/resotocore:2.0.0a18
    depends_on:
      - graphdb
    ports:
      - 8900:8900
    environment:
      - PSK
      - RESOTOCORE_HOST=resotocore
      - RESOTOCORE_UI_PATH=/usr/local/resoto/ui/
      - RESOTOCORE_START_COLLECT_ON_SUBSCRIBER_CONNECT=true
      - RESOTOCORE_TSDB_PROXY_URL=http://tsdb:9090
      - RESOTOCORE_GRAPHDB_SERVER=http://graphdb:8529
      - RESOTOCORE_GRAPHDB_PASSWORD=changeme
    restart: always
    stop_grace_period: 2m
  resotoworker: 
    image: somecr.io/someengineering/resotoworker:2.0.0a18
    depends_on:
      - resotocore
    ports:
      - 9956:9956
    environment:
      - PSK
      - RESOTOWORKER_RESOTOCORE_URI=http://resotocore:8900
      - RESOTOWORKER_RESOTOCORE_WS_URI=ws://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotometrics: 
    image: somecr.io/someengineering/resotometrics:2.0.0a18
    depends_on:
      - resotocore
    ports:
      - 9955:9955
    environment:
      - PSK
      - RESOTOMETRICS_RESOTOCORE_URI=http://resotocore:8900
      - RESOTOMETRICS_RESOTOCORE_WS_URI=ws://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotoshell: 
    image: somecr.io/someengineering/resotoshell:2.0.0a18
    depends_on:
      - resotocore
    environment:
      - PSK
      - RESOTOSHELL_RESOTOCORE_URI=http://resotocore:8900
      - RESOTOSHELL_RESOTOCORE_WS_URI=ws://resotocore:8900
    restart: always
    stop_grace_period: 2m
volumes:
  resoto_graphdb_data:
  resoto_tsdb_data:
