apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resoto.fullname" . }}-resotoworker
  labels:
    resoto: worker
    {{- include "resoto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      resoto: worker
      {{- include "resoto.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        resoto: worker
        {{- include "resoto.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resoto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          args:
          - --collector
          - {{ .Values.resotoworker.collector }}
          - --resotocore-uri
          - http://{{ include "resoto.fullname" . }}-resotocore:{{ .Values.resotocore.service.port }}
          - --resotocore-ws-uri
          - ws://{{ include "resoto.fullname" . }}-resotocore:{{ .Values.resotocore.service.port }}
          {{- if .Values.resotoworker.extraArgs }}
          {{- toYaml .Values.resotoworker.extraArgs | nindent 10 }}
          {{- end }}
          env:
            - name: START_STACK
              value: "false"
            - name: START_RESOTOWORKER
              value: "true"
            - name: PSK
              valueFrom:
                secretKeyRef:
                  name: {{ include "resoto.fullname" . }}-psk
                  key: "psk"

          {{- if .Values.resotoworker.extraEnv }}
          {{- toYaml .Values.resotoworker.extraEnv | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9956
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- if .Values.resotoworker.volumeMounts }}
          volumeMounts:
    {{- toYaml .Values.resotoworker.volumeMounts | nindent 12 }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.resotoworker.volumes }}
      volumes:
{{ toYaml .Values.resotoworker.volumes | nindent 8 }}
{{- end }}
