name: 🐛 Bug Report
description: Report a problem
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug or issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Cloudkeeper are you running?
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description:
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Please tell us how we can reproduce the undesired behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. (This will be automatically formatted into code, so no need for backticks.)
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this bug report, you agree to follow our [Code of Conduct](https://github.com/someengineering/cloudkeeper/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the Code of Conduct
          required: true
