global:
  scrape_interval: 120s
  evaluation_interval: 120s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fixcore"
    static_configs:
      - targets: ["localhost:8900"]

  - job_name: "fixmetrics"
    static_configs:
      - targets: ["localhost:9955"]

  - job_name: "fixworker"
    static_configs:
      - targets: ["localhost:9956"]
