apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resoto.fullname" . }}-resotocore
  labels:
    resoto: core
    {{- include "resoto.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      resoto: core
      {{- include "resoto.selectorLabels" . | nindent 6 }}
  # We can remove/change the strategy when the core no longer assumes it is a singleton.
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        resoto: core
        {{- include "resoto.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resoto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --host
            - {{ .Values.resotocore.host | default "0.0.0.0" | quote }}
            - --start-collect-on-subscriber-connect
            - --graphdb-server
            - {{ .Values.resotocore.graphdb.server | quote }}
            - --graphdb-database
            - {{ .Values.resotocore.graphdb.database | quote }}
            - --graphdb-username
            - {{ .Values.resotocore.graphdb.login | quote }}
            {{- if .Values.resotocore.tsdbProxyUrl }}
            - --tsdb-proxy-url
            - {{ .Values.resotocore.tsdbProxyUrl | quote }}
            {{- end }}
          env:
          - name: START_STACK
            value: "false"
          - name: START_RESOTOCORE
            value: "true"
          {{- if .Values.resotocore.graphdb.passwordSecret }}
          - name: RESOTOCORE_GRAPHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resotocore.graphdb.passwordSecret.name }}
                key: {{ .Values.resotocore.graphdb.passwordSecret.key }}
          {{- end }}
          - name: PSK
            valueFrom:
              secretKeyRef:
                name: {{ include "resoto.fullname" . }}-psk
                key: "psk"

          ports:
            - name: http
              containerPort: 8900
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /system/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
