name: Check PR (Documentation)

on: 
  push:
    branches: 
      - '!main'
    paths:
      - 'docs/**'

jobs:
  documentation:
    name: "documentation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"