name: Check PR (fixshell)
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
  pull_request:
    paths:
      - 'fixshell/**'
      - 'fixlib/**'
      - '.github/**'
      - 'requirements-all.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  fixshell:
    name: "fixshell"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('./fixshell/pyproject.toml')}}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox wheel flake8 build
          pip install --upgrade --editable fixlib/

      - name: Run tests
        working-directory: ./fixshell
        run: tox

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: fixshell-code-coverage-report
          path: fixshell/htmlcov/

      - name: Build a binary wheel and a source tarball
        working-directory: ./fixshell
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_FIXINVENTORYSHELL }}
          packages_dir: ./fixshell/dist/
