name: Check PR (cloudkeeperV1)
on:
  push:
    paths:
      - 'cloudkeeperV1/**'
      - 'cklib/**'
      - '.github/**'
    branches:
        - main
  pull_request:
    paths:
      - 'cloudkeeperV1/**'
      - 'cklib/**'
      - '.github/**'

jobs:
  cloudkeeperV1:
    name: "cloudkeeperV1"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: $\{\{runner.os}}-pip-$\{\{hashFiles('setup.py')}}
          restore-keys: |
            $\{\{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --editable cklib/
          pip install --upgrade --editable cloudkeeperV1/
          pip install tox wheel flake8

      - name: Build cklib
        working-directory: ./cklib
        run: |
          sudo rm -fr /build
          sudo mkdir -p /build -m a+rw
          pip wheel -w /build .

      - name: Build cloudkeeperV1
        working-directory: ./cloudkeeperV1
        run: |
          pip wheel -w /build -f /build .

      - name: Run tests
        working-directory: ./cloudkeeperV1
        run: tox
