name: Check PR (Documentation)

on: 
  push:
    paths:
      - 'docs/**'

jobs:
  test_documentation:
    name: "test_documentation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"