name: Check PR (resotoshell)
on:
  push:
    branches:
        - main
  pull_request:
    paths:
      - 'resotoshell/**'
      - 'resotolib/**'
      - '.github/**'

jobs:
  resotoshell:
    name: "resotoshell"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: $\{\{runner.os}}-pip-$\{\{hashFiles('setup.py')}}
          restore-keys: |
            $\{\{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox flake8

      - name: Run tests
        working-directory: ./resotoshell
        run: tox

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: resotoshell-code-coverage-report
          path: resotoshell/htmlcov/
