name: Check Pull Request
on:
    - push
jobs:
    lint-and-test:
        name: "Checkout, Lint and Test"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./keepercore
        services:
            arangodb:
                image: arangodb:3.8
                env:
                    ARANGO_ROOT_PASSWORD: root
                ports:
                    - 8529:8529
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
                  architecture: 'x64'
            - name: Restore dependency cache
              uses: actions/cache@v2
              with:
                  # This path is specific to Ubuntu
                  path: ~/.cache/pip
                  # Look to see if there is a cache hit for the corresponding requirements file
                  key: ${{runner.os}}-pip-${{hashFiles('requirements.txt')}}-${{hashFiles('requirements-dev.txt')}}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
                  pip install -r requirements.txt
                  mypy core tests > /dev/null 2>&1 || true
                  mypy --install-types --non-interactive || true
            - name: Check Formatting
              run: black --line-length 120 --check core tests
            - name: Lint
              run: |
                flake8 core
                pylint core
            - name: MyPy
              run: mypy --strict core tests
            - name: Run Tests
              run: pytest
