name: Check PR (cklib)
on:
  push:
    paths:
      - 'cklib/**'
      - '.github/**'
  pull_request:
    paths:
      - 'cklib/**'
      - '.github/**'

jobs:
  cklib:
    name: "cklib"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: $\{\{runner.os}}-pip-$\{\{hashFiles('setup.py')}}
          restore-keys: |
            $\{\{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox wheel flake8

      - name: Run tests
        working-directory: ./cklib
        run: tox
