name: Check PR (Documentation)

on: 
  push:
    branches: 
      - '!main'
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  test_documentation:
    name: "test_documentation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
