name: Compile Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'

jobs:
  deploy_documentation:
    name: "deploy_documentation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation
      run: |
        git clone https://github.com/someengineering/resoto.git --single-branch gh-pages
        cd gh-pages
        git switch --orphan gh-pages
        cd ..
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        echo 'docs.some.engineering' > CNAME
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a --allow-empty
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push documentation
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
