name: Build Docker Images

on:
    push:
        tags:
            - "*.*.*"
        branches:
            - main
    pull_request:
        paths:
            - 'Dockerfile'
            - 'docker/**'
            - '.github/workflows/docker-build.yml'
    workflow_dispatch:

jobs:
    build:
        name: Build Docker Images
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository
                uses: actions/checkout@v2
                with:
                    lfs: true

            -   name: Check out LFS objects
                run: git lfs checkout

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3
                with:
                    images: |
                        someengineering/resoto
                        ghcr.io/someengineering/resoto
                    flavor: |
                      latest=auto
                    tags: |
                        type=pep440,pattern={{version}}
                        type=pep440,pattern={{major}}.{{minor}}
                        type=pep440,pattern={{major}}
                        type=sha,prefix=
                        type=edge

            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v1

            -   name: Log in to Docker Hub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USER }}
                    password: ${{ secrets.DOCKERHUB_PASS }}

            -   name: Log in to GitHub Container Registry
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile
                    platforms: linux/amd64
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        SOURCE_COMMIT=${{ github.sha }}
                        TESTS=false
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
