name: Lint (ckcore)
on:
    push:
        paths:
            - 'ckcore/**'
            - '.github/**'

jobs:
    lint-and-test:
        name: "Checkout, Lint and Test"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./ckcore
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.7'
                  architecture: 'x64'
            - name: Restore dependency cache
              uses: actions/cache@v2
              with:
                  # This path is specific to Ubuntu
                  path: ~/.cache/pip
                  # Look to see if there is a cache hit for the corresponding requirements file
                  key: ${{runner.os}}-pip-${{hashFiles('requirements.txt')}}-${{hashFiles('requirements-dev.txt')}}-${{hashFiles('requirements-test.txt')}}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade --editable ../cklib
                  pip install -r requirements-dev.txt
                  pip install -r requirements-test.txt
                  pip install -r requirements.txt
                  mypy core tests > /dev/null 2>&1 || true
                  mypy --install-types --non-interactive || true
            - name: Check Formatting
              run: black --line-length 120 --check core tests
            - name: Lint
              run: |
                flake8 core
                pylint core
            - name: MyPy
              run: mypy core tests
