name: Check PR (resotoshell)
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
  workflow_dispatch:

jobs:
  resotoshell:
    name: "resotoshell"
    runs-on: macos-latest
    steps:
      # TODO: wait for the release to be available on PyPI
      - name: Bump homebrew
        if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.SOME_CI_PAT }}
        run: |
          git config --global user.email "ci@some.engineering"
          git config --global user.name "Some CI"
          git clone "https://$GITHUB_TOKEN@github.com/someengineering/homebrew-tap.git"
          cp requirements.txt homebrew-tap/requirements-resoto.txt
          cd homebrew-tap
          TAG_NAME=${{ github.ref }}
          TAG_NAME=${TAG_NAME#refs/tags/}
          TAG_NAME=${TAG_NAME#refs/heads/}
          BRANCH_NAME="ci/bump-resotoshell-$TAG_NAME"
          git checkout -b "$BRANCH_NAME"
          make resotoshell
          if ! git diff --quiet; then
            git commit -am "Bump resotoshell to $TAG_NAME"
            git push origin "$BRANCH_NAME"
            gh pr create --title "Bump resotoshell to $TAG_NAME" --body "" --base main --head "$BRANCH_NAME"
          else
            echo "No changes to commit"
          fi
