name: Lint (resotocore)
on:
  push:
    branches:
      - main
    paths:
      - 'resotocore/**'
      - '.github/**'
      - 'requirements-all.txt'
  pull_request:
    paths:
      - 'resotocore/**'
      - '.github/**'
      - 'requirements-all.txt'

jobs:
  resotocore-lint:
    name: "Lint (resotocore)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{runner.os}}-pip-${{hashFiles('./resotocore/pyproject.toml')}}-${{hashFiles('./resotocore/requirements-dev.txt')}}-${{hashFiles('./resotocore/requirements-test.txt')}}
      - name: Install Dependencies
        run: ./setup_venv.sh --dev --no-venv --no-plugins
      - name: Check Formatting
        working-directory: ./resotocore
        run: black --line-length 120 --check resotocore tests
      - name: Lint
        working-directory: ./resotocore
        run: |
          flake8 resotocore
          pylint resotocore
      - name: MyPy
        working-directory: ./resotocore
        run: mypy --install-types --non-interactive --strict resotocore tests
