name:  Publish resotobundle
on: workflow_dispatch:

jobs:
  resotobundle:
    name: "resotobundle"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: $\{\{runner.os}}-pip-$\{\{hashFiles('poetry.lock')}}
          restore-keys: |
            $\{\{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build a binary wheel and a source tarball
        working-directory: ./resoto-bundle
        run: |
          poetry build

      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_RESOTOBUNDLE }}
          packages_dir: ./resoto-bundle/dist/
