name: Test and build (resotocore)
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
    paths:
      - 'resotocore/**'
      - '.github/**'
  pull_request:
    paths:
      - 'resotocore/**'
      - '.github/**'

jobs:
  resotocore-test-and-build:
    name: "Test and build (resotocore)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./resotocore
    services:
      arangodb:
        image: arangodb:3.8.3
        env:
          ARANGO_NO_AUTH: 1
        ports:
          - 8529:8529
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 'pypy-3.9-v7.3.9'
          architecture: 'x64'
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{runner.os}}-pip-${{hashFiles('./resotocore/requirements.txt')}}-${{hashFiles('./resotocore/requirements-dev.txt')}}-${{hashFiles('./resotocore/requirements-test.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --editable ../resotolib
          pip install -r requirements-test.txt
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Run Tests
        env:
          RESOTOCORE_ANALYTICS_OPT_OUT: true
        run: pytest
      - name: Set up CPython for jupyter lite
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Build Jupyter lite static assets
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-jupyterlite.txt
          jupyter lite build --config jupyter_lite_config.json
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_RESOTOCORE }}
          packages_dir: ./resotocore/dist/
