name: Build Docker images

on:
    push:
        tags:
            - '*.*.*'
        branches:
            - main
    pull_request:
        paths:
            - 'Dockerfile.*'
            - 'dockerV2/**'
            - '.github/workflows/split-docker-build.yml'
    workflow_dispatch:

jobs:
    build:
        name: Build Docker Images
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository
                uses: actions/checkout@v2

            -   name: Docker resotobase meta
                id: basemeta
                uses: docker/metadata-action@v3
                with:
                    images: |
                        someengineering/resotobase
                        ghcr.io/someengineering/resotobase
                    flavor: |
                      latest=auto
                    tags: |
                        type=pep440,pattern={{version}}
                        type=pep440,pattern={{major}}.{{minor}}
                        type=pep440,pattern={{major}}
                        type=sha,format=long,prefix=
                        type=edge

            -   name: Docker resotocore meta
                id: coremeta
                uses: docker/metadata-action@v3
                with:
                    images: |
                        someengineering/resotocore
                        ghcr.io/someengineering/resotocore
                    flavor: |
                      latest=auto
                    tags: |
                        type=pep440,pattern={{version}}
                        type=pep440,pattern={{major}}.{{minor}}
                        type=pep440,pattern={{major}}
                        type=sha,prefix=
                        type=edge

            -   name: Docker resotoworker meta
                id: workermeta
                uses: docker/metadata-action@v3
                with:
                    images: |
                        someengineering/resotoworker
                        ghcr.io/someengineering/resotoworker
                    flavor: |
                      latest=auto
                    tags: |
                        type=pep440,pattern={{version}}
                        type=pep440,pattern={{major}}.{{minor}}
                        type=pep440,pattern={{major}}
                        type=sha,prefix=
                        type=edge

            -   name: Docker resotometrics meta
                id: metricsmeta
                uses: docker/metadata-action@v3
                with:
                    images: |
                        someengineering/resotometrics
                        ghcr.io/someengineering/resotometrics
                    flavor: |
                      latest=auto
                    tags: |
                        type=pep440,pattern={{version}}
                        type=pep440,pattern={{major}}.{{minor}}
                        type=pep440,pattern={{major}}
                        type=sha,prefix=
                        type=edge

            -   name: Docker resotoshell meta
                id: shellmeta
                uses: docker/metadata-action@v3
                with:
                    images: |
                        someengineering/resotoshell
                        ghcr.io/someengineering/resotoshell
                    flavor: |
                      latest=auto
                    tags: |
                        type=pep440,pattern={{version}}
                        type=pep440,pattern={{major}}.{{minor}}
                        type=pep440,pattern={{major}}
                        type=sha,prefix=
                        type=edge

            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v1

            -   name: Log in to Docker Hub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USER }}
                    password: ${{ secrets.DOCKERHUB_PASS }}

            -   name: Log in to GitHub Container Registry
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push resotobase Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile.resotobase
                    platforms: linux/amd64,linux/arm64
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        SOURCE_COMMIT=${{ github.sha }}
                        TESTS=false
                    tags: ${{ steps.basemeta.outputs.tags }}
                    labels: ${{ steps.basemeta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

            -   name: Build and push resotocore Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile.resotocore
                    platforms: linux/amd64,linux/arm64
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        IMAGE_TAG=${{ github.sha }}
                    tags: ${{ steps.coremeta.outputs.tags }}
                    labels: ${{ steps.coremeta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

            -   name: Build and push resotoworker Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile.resotoworker
                    platforms: linux/amd64,linux/arm64
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        IMAGE_TAG=${{ github.sha }}
                    tags: ${{ steps.workermeta.outputs.tags }}
                    labels: ${{ steps.workermeta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

            -   name: Build and push resotometrics Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile.resotometrics
                    platforms: linux/amd64,linux/arm64
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        IMAGE_TAG=${{ github.sha }}
                    tags: ${{ steps.metricsmeta.outputs.tags }}
                    labels: ${{ steps.metricsmeta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

            -   name: Build and push resotoshell Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile.resotoshell
                    platforms: linux/amd64,linux/arm64
                    push: ${{ github.event_name != 'pull_request' }}
                    build-args: |
                        IMAGE_TAG=${{ github.sha }}
                    tags: ${{ steps.shellmeta.outputs.tags }}
                    labels: ${{ steps.shellmeta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
